# -*- coding: utf-8 -*-
"""D-wave Ising solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116GmM4K3m34AEwlc8M0LQM8qsIFRRcz3
"""

pip install dwave-ocean-sdk

!dwave setup

from dwave.system import DWaveSampler, EmbeddingComposite
import dwavebinarycsp
import numpy as np
import itertools
# Set a constant seed for reproducibility
random_seed = 42
# Define the Ising model parameters
# Define the interaction matrix J with random values
J = np.random.uniform(-1, 1, size=(10, 10))
# Generate all possible spin configurations
spin_configurations = list(itertools.product([-1, 1], repeat=10))

# Define the Ising model parameters
# Convert the problem to a QUBO
h = {}
J_dict = {(i, j): J[i, j] for i in range(10) for j in range(i, 10)}

# Set up the solver
sampler = EmbeddingComposite(DWaveSampler())

# Solve the problem
response = sampler.sample_ising(h, J_dict, num_reads=1000)

# Extract the best solution
best_solution = response.first.sample
best_energy = response.first.energy

print(f"D-Wave ground state: {best_solution}")
print(f"D-Wave ground energy: {best_energy}")